/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'lab' : IDL.Null,
  'admin' : IDL.Null,
  'director' : IDL.Null,
  'purchaser' : IDL.Null,
  'official' : IDL.Null,
});
export const ApplianceCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
});
export const Brand = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'applianceCategoryId' : IDL.Nat,
});
export const Lab = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'allocationPercentage' : IDL.Nat,
  'location' : IDL.Text,
});
export const Model = IDL.Record({
  'id' : IDL.Nat,
  'starRating' : IDL.Nat,
  'applianceCategoryId' : IDL.Nat,
  'modelNumber' : IDL.Text,
  'brandId' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
});
export const FinancialRecord = IDL.Record({
  'id' : IDL.Nat,
  'instalments' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Text, IDL.Text)),
  'totalApprovedAmount' : IDL.Nat,
  'state' : IDL.Text,
});
export const Sample = IDL.Record({
  'id' : IDL.Nat,
  'financialYear' : IDL.Text,
  'status' : IDL.Text,
  'starRating' : IDL.Nat,
  'invoiceUrl' : IDL.Opt(IDL.Text),
  'testReportUrl' : IDL.Opt(IDL.Text),
  'testDate' : IDL.Opt(IDL.Text),
  'applianceCategoryId' : IDL.Nat,
  'notFitReason' : IDL.Opt(IDL.Text),
  'labId' : IDL.Nat,
  'purchaserId' : IDL.Text,
  'state' : IDL.Text,
  'brandId' : IDL.Nat,
  'targetId' : IDL.Nat,
  'remarks' : IDL.Opt(IDL.Text),
  'modelId' : IDL.Nat,
});
export const TestReport = IDL.Record({
  'id' : IDL.Nat,
  'reportUrl' : IDL.Text,
  'result' : IDL.Text,
  'submittedAt' : IDL.Text,
  'reviewStatus' : IDL.Text,
  'labId' : IDL.Nat,
  'reviewedBy' : IDL.Opt(IDL.Text),
  'reviewRemarks' : IDL.Opt(IDL.Text),
  'sampleId' : IDL.Nat,
});
export const Target = IDL.Record({
  'id' : IDL.Nat,
  'financialYear' : IDL.Text,
  'status' : IDL.Text,
  'starRating' : IDL.Nat,
  'assignedTo' : IDL.Text,
  'createdBy' : IDL.Text,
  'applianceCategoryId' : IDL.Nat,
  'state' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const OfficialAssignment = IDL.Record({
  'id' : IDL.Nat,
  'applianceCategoryId' : IDL.Nat,
  'officialId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveReport' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignOfficialToCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'assignSampleToLab' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'blockSample' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createApplianceCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createBrand' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'createFinancialRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Text, IDL.Text)),
      ],
      [],
      [],
    ),
  'createLab' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createModel' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'createTarget' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Role,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'getAllApplianceCategories' : IDL.Func(
      [],
      [IDL.Vec(ApplianceCategory)],
      ['query'],
    ),
  'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getAllLabs' : IDL.Func([], [IDL.Vec(Lab)], ['query']),
  'getAllModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [IDL.Text], ['query']),
  'getFinancialMonitoring' : IDL.Func(
      [],
      [IDL.Vec(FinancialRecord)],
      ['query'],
    ),
  'getLabTestMonitoring' : IDL.Func([], [IDL.Vec(Sample)], ['query']),
  'getMyAssignedSamples' : IDL.Func([], [IDL.Vec(Sample)], ['query']),
  'getMyReports' : IDL.Func([], [IDL.Vec(TestReport)], ['query']),
  'getMyTargets' : IDL.Func([], [IDL.Vec(Target)], ['query']),
  'getOfficialAssignments' : IDL.Func(
      [],
      [IDL.Vec(OfficialAssignment)],
      ['query'],
    ),
  'getTargets' : IDL.Func([], [IDL.Vec(Target)], ['query']),
  'getUser' : IDL.Func([IDL.Text], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseSample' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'rejectReport' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'revertReport' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProduct' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Vec(Sample)],
      ['query'],
    ),
  'submitReportToBEEOfficial' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSampleStatus' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateTarget' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Role,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'uploadTestReport' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'lab' : IDL.Null,
    'admin' : IDL.Null,
    'director' : IDL.Null,
    'purchaser' : IDL.Null,
    'official' : IDL.Null,
  });
  const ApplianceCategory = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Brand = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'applianceCategoryId' : IDL.Nat,
  });
  const Lab = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'allocationPercentage' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Model = IDL.Record({
    'id' : IDL.Nat,
    'starRating' : IDL.Nat,
    'applianceCategoryId' : IDL.Nat,
    'modelNumber' : IDL.Text,
    'brandId' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
  });
  const FinancialRecord = IDL.Record({
    'id' : IDL.Nat,
    'instalments' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Text, IDL.Text)),
    'totalApprovedAmount' : IDL.Nat,
    'state' : IDL.Text,
  });
  const Sample = IDL.Record({
    'id' : IDL.Nat,
    'financialYear' : IDL.Text,
    'status' : IDL.Text,
    'starRating' : IDL.Nat,
    'invoiceUrl' : IDL.Opt(IDL.Text),
    'testReportUrl' : IDL.Opt(IDL.Text),
    'testDate' : IDL.Opt(IDL.Text),
    'applianceCategoryId' : IDL.Nat,
    'notFitReason' : IDL.Opt(IDL.Text),
    'labId' : IDL.Nat,
    'purchaserId' : IDL.Text,
    'state' : IDL.Text,
    'brandId' : IDL.Nat,
    'targetId' : IDL.Nat,
    'remarks' : IDL.Opt(IDL.Text),
    'modelId' : IDL.Nat,
  });
  const TestReport = IDL.Record({
    'id' : IDL.Nat,
    'reportUrl' : IDL.Text,
    'result' : IDL.Text,
    'submittedAt' : IDL.Text,
    'reviewStatus' : IDL.Text,
    'labId' : IDL.Nat,
    'reviewedBy' : IDL.Opt(IDL.Text),
    'reviewRemarks' : IDL.Opt(IDL.Text),
    'sampleId' : IDL.Nat,
  });
  const Target = IDL.Record({
    'id' : IDL.Nat,
    'financialYear' : IDL.Text,
    'status' : IDL.Text,
    'starRating' : IDL.Nat,
    'assignedTo' : IDL.Text,
    'createdBy' : IDL.Text,
    'applianceCategoryId' : IDL.Nat,
    'state' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const OfficialAssignment = IDL.Record({
    'id' : IDL.Nat,
    'applianceCategoryId' : IDL.Nat,
    'officialId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveReport' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignOfficialToCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'assignSampleToLab' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'blockSample' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createApplianceCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createBrand' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'createFinancialRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Text, IDL.Text)),
        ],
        [],
        [],
      ),
    'createLab' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createModel' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'createTarget' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Role,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'getAllApplianceCategories' : IDL.Func(
        [],
        [IDL.Vec(ApplianceCategory)],
        ['query'],
      ),
    'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getAllLabs' : IDL.Func([], [IDL.Vec(Lab)], ['query']),
    'getAllModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [IDL.Text], ['query']),
    'getFinancialMonitoring' : IDL.Func(
        [],
        [IDL.Vec(FinancialRecord)],
        ['query'],
      ),
    'getLabTestMonitoring' : IDL.Func([], [IDL.Vec(Sample)], ['query']),
    'getMyAssignedSamples' : IDL.Func([], [IDL.Vec(Sample)], ['query']),
    'getMyReports' : IDL.Func([], [IDL.Vec(TestReport)], ['query']),
    'getMyTargets' : IDL.Func([], [IDL.Vec(Target)], ['query']),
    'getOfficialAssignments' : IDL.Func(
        [],
        [IDL.Vec(OfficialAssignment)],
        ['query'],
      ),
    'getTargets' : IDL.Func([], [IDL.Vec(Target)], ['query']),
    'getUser' : IDL.Func([IDL.Text], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseSample' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'rejectReport' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'revertReport' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProduct' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Vec(Sample)],
        ['query'],
      ),
    'submitReportToBEEOfficial' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSampleStatus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateTarget' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Role,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'uploadTestReport' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };