/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApplianceCategory { 'id' : bigint, 'name' : string }
export interface Brand {
  'id' : bigint,
  'name' : string,
  'applianceCategoryId' : bigint,
}
export interface FinancialRecord {
  'id' : bigint,
  'instalments' : Array<[bigint, bigint, string, string]>,
  'totalApprovedAmount' : bigint,
  'state' : string,
}
export interface Lab {
  'id' : bigint,
  'name' : string,
  'state' : string,
  'allocationPercentage' : bigint,
  'location' : string,
}
export interface Model {
  'id' : bigint,
  'starRating' : bigint,
  'applianceCategoryId' : bigint,
  'modelNumber' : string,
  'brandId' : bigint,
}
export interface OfficialAssignment {
  'id' : bigint,
  'applianceCategoryId' : bigint,
  'officialId' : string,
}
export type Role = { 'lab' : null } |
  { 'admin' : null } |
  { 'director' : null } |
  { 'purchaser' : null } |
  { 'official' : null };
export interface Sample {
  'id' : bigint,
  'financialYear' : string,
  'status' : string,
  'starRating' : bigint,
  'invoiceUrl' : [] | [string],
  'testReportUrl' : [] | [string],
  'testDate' : [] | [string],
  'applianceCategoryId' : bigint,
  'notFitReason' : [] | [string],
  'labId' : bigint,
  'purchaserId' : string,
  'state' : string,
  'brandId' : bigint,
  'targetId' : bigint,
  'remarks' : [] | [string],
  'modelId' : bigint,
}
export interface Target {
  'id' : bigint,
  'financialYear' : string,
  'status' : string,
  'starRating' : bigint,
  'assignedTo' : string,
  'createdBy' : string,
  'applianceCategoryId' : bigint,
  'state' : string,
  'quantity' : bigint,
}
export interface TestReport {
  'id' : bigint,
  'reportUrl' : string,
  'result' : string,
  'submittedAt' : string,
  'reviewStatus' : string,
  'labId' : bigint,
  'reviewedBy' : [] | [string],
  'reviewRemarks' : [] | [string],
  'sampleId' : bigint,
}
export interface User {
  'id' : string,
  'name' : string,
  'role' : Role,
  'isActive' : boolean,
  'email' : string,
  'state' : [] | [string],
  'department' : [] | [string],
}
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'email' : string,
  'state' : [] | [string],
  'department' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveReport' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignOfficialToCategory' : ActorMethod<[bigint, string, bigint], undefined>,
  'assignSampleToLab' : ActorMethod<[bigint, bigint], undefined>,
  'blockSample' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, string, string],
    undefined
  >,
  'createApplianceCategory' : ActorMethod<[bigint, string], undefined>,
  'createBrand' : ActorMethod<[bigint, string, bigint], undefined>,
  'createFinancialRecord' : ActorMethod<
    [bigint, string, bigint, Array<[bigint, bigint, string, string]>],
    undefined
  >,
  'createLab' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'createModel' : ActorMethod<
    [bigint, bigint, string, bigint, bigint],
    undefined
  >,
  'createTarget' : ActorMethod<
    [bigint, string, string, bigint, bigint, bigint, string, string],
    undefined
  >,
  'createUser' : ActorMethod<
    [string, string, string, Role, [] | [string], [] | [string]],
    undefined
  >,
  'deleteUser' : ActorMethod<[string], undefined>,
  'getAllApplianceCategories' : ActorMethod<[], Array<ApplianceCategory>>,
  'getAllBrands' : ActorMethod<[], Array<Brand>>,
  'getAllLabs' : ActorMethod<[], Array<Lab>>,
  'getAllModels' : ActorMethod<[], Array<Model>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], string>,
  'getFinancialMonitoring' : ActorMethod<[], Array<FinancialRecord>>,
  'getLabTestMonitoring' : ActorMethod<[], Array<Sample>>,
  'getMyAssignedSamples' : ActorMethod<[], Array<Sample>>,
  'getMyReports' : ActorMethod<[], Array<TestReport>>,
  'getMyTargets' : ActorMethod<[], Array<Target>>,
  'getOfficialAssignments' : ActorMethod<[], Array<OfficialAssignment>>,
  'getTargets' : ActorMethod<[], Array<Target>>,
  'getUser' : ActorMethod<[string], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseSample' : ActorMethod<[bigint, string], undefined>,
  'rejectReport' : ActorMethod<[bigint, string], undefined>,
  'revertReport' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProduct' : ActorMethod<
    [bigint, bigint, bigint, bigint, string],
    Array<Sample>
  >,
  'submitReportToBEEOfficial' : ActorMethod<
    [bigint, bigint, bigint, string, string, string],
    undefined
  >,
  'updateSampleStatus' : ActorMethod<
    [bigint, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateTarget' : ActorMethod<
    [bigint, string, string, bigint, bigint, bigint, string, string],
    undefined
  >,
  'updateUser' : ActorMethod<
    [string, string, string, Role, [] | [string], [] | [string], boolean],
    undefined
  >,
  'uploadTestReport' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];