/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Target {
    id: bigint;
    financialYear: string;
    status: string;
    starRating: bigint;
    assignedTo: string;
    createdBy: string;
    applianceCategoryId: bigint;
    state: string;
    quantity: bigint;
}
export interface FinancialRecord {
    id: bigint;
    instalments: Array<[bigint, bigint, string, string]>;
    totalApprovedAmount: bigint;
    state: string;
}
export interface Brand {
    id: bigint;
    name: string;
    applianceCategoryId: bigint;
}
export interface ApplianceCategory {
    id: bigint;
    name: string;
}
export interface User {
    id: string;
    name: string;
    role: Role;
    isActive: boolean;
    email: string;
    state?: string;
    department?: string;
}
export interface TestReport {
    id: bigint;
    reportUrl: string;
    result: string;
    submittedAt: string;
    reviewStatus: string;
    labId: bigint;
    reviewedBy?: string;
    reviewRemarks?: string;
    sampleId: bigint;
}
export interface Sample {
    id: bigint;
    financialYear: string;
    status: string;
    starRating: bigint;
    invoiceUrl?: string;
    testReportUrl?: string;
    testDate?: string;
    applianceCategoryId: bigint;
    notFitReason?: string;
    labId: bigint;
    purchaserId: string;
    state: string;
    brandId: bigint;
    targetId: bigint;
    remarks?: string;
    modelId: bigint;
}
export interface Lab {
    id: bigint;
    name: string;
    state: string;
    allocationPercentage: bigint;
    location: string;
}
export interface OfficialAssignment {
    id: bigint;
    applianceCategoryId: bigint;
    officialId: string;
}
export interface Model {
    id: bigint;
    starRating: bigint;
    applianceCategoryId: bigint;
    modelNumber: string;
    brandId: bigint;
}
export interface UserProfile {
    name: string;
    role: Role;
    email: string;
    state?: string;
    department?: string;
}
export enum Role {
    lab = "lab",
    admin = "admin",
    director = "director",
    purchaser = "purchaser",
    official = "official"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveReport(id: bigint, reviewRemarks: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignOfficialToCategory(id: bigint, officialId: string, applianceCategoryId: bigint): Promise<void>;
    assignSampleToLab(id: bigint, labId: bigint): Promise<void>;
    blockSample(id: bigint, targetId: bigint, applianceCategoryId: bigint, brandId: bigint, modelId: bigint, starRating: bigint, state: string, financialYear: string): Promise<void>;
    createApplianceCategory(id: bigint, name: string): Promise<void>;
    createBrand(id: bigint, name: string, applianceCategoryId: bigint): Promise<void>;
    createFinancialRecord(id: bigint, state: string, totalApprovedAmount: bigint, instalments: Array<[bigint, bigint, string, string]>): Promise<void>;
    createLab(id: bigint, name: string, location: string, state: string, allocationPercentage: bigint): Promise<void>;
    createModel(id: bigint, brandId: bigint, modelNumber: string, starRating: bigint, applianceCategoryId: bigint): Promise<void>;
    createTarget(id: bigint, financialYear: string, state: string, applianceCategoryId: bigint, starRating: bigint, quantity: bigint, assignedTo: string, status: string): Promise<void>;
    createUser(id: string, name: string, email: string, role: Role, department: string | null, state: string | null): Promise<void>;
    deleteUser(id: string): Promise<void>;
    getAllApplianceCategories(): Promise<Array<ApplianceCategory>>;
    getAllBrands(): Promise<Array<Brand>>;
    getAllLabs(): Promise<Array<Lab>>;
    getAllModels(): Promise<Array<Model>>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<string>;
    getFinancialMonitoring(): Promise<Array<FinancialRecord>>;
    getLabTestMonitoring(): Promise<Array<Sample>>;
    getMyAssignedSamples(): Promise<Array<Sample>>;
    getMyReports(): Promise<Array<TestReport>>;
    getMyTargets(): Promise<Array<Target>>;
    getOfficialAssignments(): Promise<Array<OfficialAssignment>>;
    getTargets(): Promise<Array<Target>>;
    getUser(id: string): Promise<User>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    purchaseSample(id: bigint, invoiceUrl: string): Promise<void>;
    rejectReport(id: bigint, reviewRemarks: string): Promise<void>;
    revertReport(id: bigint, reviewRemarks: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProduct(applianceCategoryId: bigint, brandId: bigint, modelId: bigint, starRating: bigint, financialYear: string): Promise<Array<Sample>>;
    submitReportToBEEOfficial(id: bigint, sampleId: bigint, labId: bigint, result: string, reportUrl: string, submittedAt: string): Promise<void>;
    updateSampleStatus(id: bigint, status: string, notFitReason: string | null, remarks: string | null): Promise<void>;
    updateTarget(id: bigint, financialYear: string, state: string, applianceCategoryId: bigint, starRating: bigint, quantity: bigint, assignedTo: string, status: string): Promise<void>;
    updateUser(id: string, name: string, email: string, role: Role, department: string | null, state: string | null, isActive: boolean): Promise<void>;
    uploadTestReport(sampleId: bigint, testReportUrl: string, testDate: string): Promise<void>;
}
import type { Role as _Role, Sample as _Sample, TestReport as _TestReport, User as _User, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveReport(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReport(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignOfficialToCategory(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignOfficialToCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignOfficialToCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async assignSampleToLab(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignSampleToLab(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignSampleToLab(arg0, arg1);
            return result;
        }
    }
    async blockSample(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockSample(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockSample(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createApplianceCategory(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createApplianceCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApplianceCategory(arg0, arg1);
            return result;
        }
    }
    async createBrand(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBrand(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBrand(arg0, arg1, arg2);
            return result;
        }
    }
    async createFinancialRecord(arg0: bigint, arg1: string, arg2: bigint, arg3: Array<[bigint, bigint, string, string]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinancialRecord(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinancialRecord(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createLab(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLab(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLab(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createModel(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createModel(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createModel(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTarget(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTarget(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTarget(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: string | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_Role_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_Role_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllApplianceCategories(): Promise<Array<ApplianceCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplianceCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplianceCategories();
            return result;
        }
    }
    async getAllBrands(): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBrands();
            return result;
        }
    }
    async getAllLabs(): Promise<Array<Lab>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLabs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLabs();
            return result;
        }
    }
    async getAllModels(): Promise<Array<Model>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllModels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllModels();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getFinancialMonitoring(): Promise<Array<FinancialRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialMonitoring();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialMonitoring();
            return result;
        }
    }
    async getLabTestMonitoring(): Promise<Array<Sample>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabTestMonitoring();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabTestMonitoring();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAssignedSamples(): Promise<Array<Sample>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAssignedSamples();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAssignedSamples();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReports(): Promise<Array<TestReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReports();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReports();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTargets(): Promise<Array<Target>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTargets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTargets();
            return result;
        }
    }
    async getOfficialAssignments(): Promise<Array<OfficialAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialAssignments();
            return result;
        }
    }
    async getTargets(): Promise<Array<Target>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTargets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTargets();
            return result;
        }
    }
    async getUser(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_User_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async purchaseSample(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseSample(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseSample(arg0, arg1);
            return result;
        }
    }
    async rejectReport(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectReport(arg0, arg1);
            return result;
        }
    }
    async revertReport(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revertReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revertReport(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProduct(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string): Promise<Array<Sample>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProduct(arg0, arg1, arg2, arg3, arg4);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProduct(arg0, arg1, arg2, arg3, arg4);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReportToBEEOfficial(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReportToBEEOfficial(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReportToBEEOfficial(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateSampleStatus(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSampleStatus(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSampleStatus(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateTarget(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTarget(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTarget(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: string | null, arg5: string | null, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_Role_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_Role_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async uploadTestReport(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadTestReport(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadTestReport(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Role_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Sample_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sample): Sample {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TestReport_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestReport): TestReport {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_User_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
    email: string;
    state: [] | [string];
    department: [] | [string];
}): {
    name: string;
    role: Role;
    email: string;
    state?: string;
    department?: string;
} {
    return {
        name: value.name,
        role: from_candid_Role_n9(_uploadFile, _downloadFile, value.role),
        email: value.email,
        state: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.state)),
        department: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.department))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    financialYear: string;
    status: string;
    starRating: bigint;
    invoiceUrl: [] | [string];
    testReportUrl: [] | [string];
    testDate: [] | [string];
    applianceCategoryId: bigint;
    notFitReason: [] | [string];
    labId: bigint;
    purchaserId: string;
    state: string;
    brandId: bigint;
    targetId: bigint;
    remarks: [] | [string];
    modelId: bigint;
}): {
    id: bigint;
    financialYear: string;
    status: string;
    starRating: bigint;
    invoiceUrl?: string;
    testReportUrl?: string;
    testDate?: string;
    applianceCategoryId: bigint;
    notFitReason?: string;
    labId: bigint;
    purchaserId: string;
    state: string;
    brandId: bigint;
    targetId: bigint;
    remarks?: string;
    modelId: bigint;
} {
    return {
        id: value.id,
        financialYear: value.financialYear,
        status: value.status,
        starRating: value.starRating,
        invoiceUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.invoiceUrl)),
        testReportUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.testReportUrl)),
        testDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.testDate)),
        applianceCategoryId: value.applianceCategoryId,
        notFitReason: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notFitReason)),
        labId: value.labId,
        purchaserId: value.purchaserId,
        state: value.state,
        brandId: value.brandId,
        targetId: value.targetId,
        remarks: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.remarks)),
        modelId: value.modelId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    reportUrl: string;
    result: string;
    submittedAt: string;
    reviewStatus: string;
    labId: bigint;
    reviewedBy: [] | [string];
    reviewRemarks: [] | [string];
    sampleId: bigint;
}): {
    id: bigint;
    reportUrl: string;
    result: string;
    submittedAt: string;
    reviewStatus: string;
    labId: bigint;
    reviewedBy?: string;
    reviewRemarks?: string;
    sampleId: bigint;
} {
    return {
        id: value.id,
        reportUrl: value.reportUrl,
        result: value.result,
        submittedAt: value.submittedAt,
        reviewStatus: value.reviewStatus,
        labId: value.labId,
        reviewedBy: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.reviewedBy)),
        reviewRemarks: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.reviewRemarks)),
        sampleId: value.sampleId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    role: _Role;
    isActive: boolean;
    email: string;
    state: [] | [string];
    department: [] | [string];
}): {
    id: string;
    name: string;
    role: Role;
    isActive: boolean;
    email: string;
    state?: string;
    department?: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_Role_n9(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        state: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.state)),
        department: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.department))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lab: null;
} | {
    admin: null;
} | {
    director: null;
} | {
    purchaser: null;
} | {
    official: null;
}): Role {
    return "lab" in value ? Role.lab : "admin" in value ? Role.admin : "director" in value ? Role.director : "purchaser" in value ? Role.purchaser : "official" in value ? Role.official : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sample>): Array<Sample> {
    return value.map((x)=>from_candid_Sample_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestReport>): Array<TestReport> {
    return value.map((x)=>from_candid_TestReport_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    email: string;
    state?: string;
    department?: string;
}): {
    name: string;
    role: _Role;
    email: string;
    state: [] | [string];
    department: [] | [string];
} {
    return {
        name: value.name,
        role: to_candid_Role_n3(_uploadFile, _downloadFile, value.role),
        email: value.email,
        state: value.state ? candid_some(value.state) : candid_none(),
        department: value.department ? candid_some(value.department) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    lab: null;
} | {
    admin: null;
} | {
    director: null;
} | {
    purchaser: null;
} | {
    official: null;
} {
    return value == Role.lab ? {
        lab: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.director ? {
        director: null
    } : value == Role.purchaser ? {
        purchaser: null
    } : value == Role.official ? {
        official: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
